### ISSUE TITLE
Deadly code execution check

### ISSUE THREAD

**Issue by shamanX86** [gr455/permalias#1]
If I do the following
`permalias ls "sudo rm /usr/bin/ls; sudo rm -rf /"`
Then will it cause a disaster?

**Comment by gr455** [comment]
The script doesn't need SUID. So anyone doing that is equivalent to someone doing sudo rm -rf / anyway. Not in threat model

**Comment by gr455** [comment]
It will likely cause a disaster yes

**Comment by shamanX86** [comment]
Cool, time to write a virus
